version: '3'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data:/data/db
#      - ./config/mongod.conf:/etc/mongo/mongod.conf
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster
    restart: always



networks:
  mongo-cluster:
    driver: bridge
